config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    member do
      get 'like', to: "posts#upvote"
      get 'dislike', to: "posts#downvote"
    end
    resources :comments
  end

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  
  belongs_to :user
  has_many :comments

  has_attached_file :image, styles: { medium: "700x300#", small: "350x250>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.post_id = @post.id

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, execpt: [:index, :show]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @comments = Comment.where(post_id: @post)
    @random_post = Post.where.not(id: @post).order("RANDOM()").first
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_by current_user
    redirect_to :back
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
	= f.input :content, label: "Reply to thread"
	= f.button :submit, class: "button"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Muse
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application'
  %link{ :rel => 'stylesheet', :href => '//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'}
  %link{ :rel => 'stylesheet', :href => 'path/to/font-awesome/css/font-awesome.min.css'}
%body
  %header
    .wrapper.clearfix
      #logo= link_to "Muse", root_path
      %nav
        - if user_signed_in?
          = link_to current_user.name, edit_user_registration_path
          = link_to "Add New Inspiration", new_post_path, class: "button"
        - else
          = link_to "Sign In", new_user_session_path
          = link_to "Sign Up", new_user_registration_path, class: "button"
  %p.notice= notice
  %p.alert= alert

  .wrapper
    = yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :title
  = f.input :link
  = f.input :description
  = f.input :image
  = f.button :submit

app/views/posts/edit.html.haml
%h1 Edit

= render 'form'

app/views/posts/index.html.haml
- if user_signed_in?
  %p#intro
    Hello
    = current_user.name
    %br/
    %span
      Share your Inspiration and see what's inspiring others.
- else
  %p#intro
    What'is your muse?
    %br/
    %span
      Share your Inspiration and see what's inspiring others.

#posts
  - @posts.each do |p|
    .post
      .post_image
        = link_to (image_tag p.image.url(:small)), p
      .post_content
        .title
          %h2=  link_to p.title, p
        .data.clearfix
          %p.username
            Shared by
            = p.user.name
          %p.button
            %span
              %i.fa.fa-comments-o
              = p.comments.count
            %span
              %i.fa.fa-thumbs-o-up
              = p.get_likes.size

app/views/posts/new.html.haml
%h1 New POst

= render 'form' 

app/views/posts/show.html.haml
#post_show
  %h1= @post.title
  %p.username
    Share by
    = @post.user.name
    about
    = time_ago_in_words(@post.created_at)
  .clearfix
    .post_image_description
      = image_tag @post.image.url(:medium)
      .descritption= simple_format(@post.description)
    .post_data
      = link_to "Visit Link", @post.link, class: "button"
      = link_to like_post_path(@post), method: :get, class: "data" do
        %i.fa.fa-thumbs-o-up
        = pluralize(@post.get_upvotes.size, "Like")
      = link_to like_post_path(@post), method: :get, class: "data" do
        %i.fa.fa-thumbs-o-down
        = pluralize(@post.get_downvotes.size, "DisLike")
      %p.data
        %i.fa.fa-comments-o
        = pluralize(@post.comments.count, "Comment")
      - if @post.user == current_user
        = link_to "Edit", edit_post_path(@post), class: "data"
        = link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure"}, class: "data"
    #random_post
      %h3 Random Inspiration
      .post
        .post_image
          = link_to (image_tag @random_post.image.url(:small)), post_path(@random_post)
        .post_content
          .title
            %h2= link_to @random_post.title, post_path(@random_post)
          .data.clearfix
            Shared by
            = @random_post.user.name
          %p.buttons
            %span
            %i.fa.fa-comments-o
            = @random_post.comments.count
            = @random_post.get_likes.size

#comments
  %h2.comment_count= pluralize(@post.comments.count, "Comment")
  - @comments.each do |comment|
    .comment
      %p.username= comment.user.name
      %p.content= comment.content
= render 'comments/form'